# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7436c553-8e3c-42c8-8f51-0e9ce25be6a4";
      fsType = "ext4";
    };

#  fileSystems."/mnt/game-night-prod" =
#    { device = "/dev/disk/by-uuid/c55fa9fa-e418-4d6f-9f61-b6bcd3e40702";
#      fsType = "ext4";
#    };
#
#  fileSystems."/mnt/game-night-backup" =
#    { device = "/dev/disk/by-uuid/c50f1b24-3b30-4f0c-98c0-a8ce6d72b20e";
#      fsType = "ext4";
#    };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/d083f112-c80d-412b-b30d-7c6551a7dc5a"; }
    ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
