name: "Packer"

on:
  pull_request:
    paths:
      - infra/images/**
      - .github/workflows/packer.yml
  push:
    branches:
      - 'main'
    paths:
      - infra/images/**
      - .github/workflows/packer.yml
  workflow_dispatch:
    branches: [main]

jobs:
  packer:
    name: CI Tests and Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Note: Hasicorp action does not support `packer fmt -check` yet >_<
    - name: Check Packer Formatting
      run: sudo apt-get install packer && cd infra/images/podman-prod && packer fmt -check .

    - name: Packer Init
      uses: hashicorp/packer-github-actions@master
      with:
        command: init
        arguments: -upgrade
        target: infra/images/podman-prod/
        working_directory: "."

    - name: Validate Packer Templates
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate 
        arguments: -syntax-only
        target: infra/images/podman-prod/
        working_directory: "."

    - name: "Build Image: podman-prod"
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: -color=false -on-error=abort
        target: infra/images/podman-prod/
        working_directory: "."
      env:
        PACKER_LOG: 1
        PKR_VAR_do_token: ${{ secrets.DO_TOKEN }}
        PKR_VAR_ssh_password: ${{ secrets.ROOT_PASSWORD }}

    # TODO - Image cleanup step or job